### ISSUE TITLE
SyntaxError: `https://email.us-east-1.amazonaws.com` node-ses/lib/ses.js:50

### ISSUE THREAD

**Issue by ogdans3** [aheckmann/node-ses#41] opened 2017-02-04 22:57 UTC
Got an error message on my server when trying to use the module. I assume its some encoding issue with the \` character, it works fine on my desktop. It seemed to function correctly when i changed the \` to the '

![image](https://cloud.githubusercontent.com/assets/8287733/22622232/611b48c8-eb35-11e6-9559-4c1232709fdc.png)

/home/ogdans3/git/haavard/node_modules/node-ses/lib/ses.js:50

Is the special quotation mark important? Do you know how I resolve the syntax error?

**Comment by markstos** [comment] 2017-02-05 23:16
Duplicate of #39.

Apparently I didn't actually publish version 2.0.3 with the fix like I thought I did. Sorry. 

Thanks for the report. Published now.

**Closed by markstos** 2017-02-05 23:16 UTC
