### ISSUE TITLE
Issue with Image which is send Via Mail in iOs default mail app & outlook

### ISSUE THREAD

**Issue by pradip-Kachhadiya** [aheckmann/node-ses#40] opened 2017-01-13 06:20 UTC
I am trying to send Email from node.js API using "node-ses". I attached image url code inside mail body.
inside my template i have also included.

`<img src="' + host + '/images/ic_comscope.png" height="40"> `
It works completely inside Gmail & browser, But having issue in iOs default mail app & outlook.

note: i don't want suggestion related to attachments

> Also base64 not works with "src" of "image" tag

Give any solution

**Comment by markstos** [comment] 2017-01-13 14:00
If the message went out, the issue is not with `node-ses`, it is with the content of your message. I think you'll find that if you send the sent message through another means, it has the same problem. 

I'm closing as not-a-bug.

**Closed by markstos** 2017-01-13 14:00 UTC
