### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by SURVESHCHAUHANMARLABS** [aheckmann/node-ses#58] opened 2020-03-18 03:28 UTC
I have set my config as below.
```
var ses = require('node-ses')
let client = ses.createClient({ key: '<my key>', secret: '<my secret>',amazon: 'https://email.ap-south-1.amazonaws.com' });
console.log(client)
// Give SES the details and let it construct the message for you.
client.sendEmail({
   to: 'akhil156@gmail.com'
 , from: 'My verified domain address email'
 , subject: 'greetings'
 , message: 'your <b>message</b> goes here'
 , altText: 'plain text'
}, function (err, data, res) {
 // ...
 if(err){
  console.log(err)
  console.log('err occured.')
 }
 else{
  console.log(data)
  console.log('mail sent..check your inbox..')
 }
});
```
I am getting the below error.
```
{
  Type: 'Sender',
  Code: 'SignatureDoesNotMatch',
  Message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'
}
```

The same config is working in aws-sdk. But I am getting this error in node-ses. Can anyone help me to figure out the problem in my setting?

**Comment by markstos** [comment] 2020-03-26 16:09
Which version of `node-ses`?

**Comment by epegzz** [comment] 2020-04-14 16:51
I'm getting the same error message. Using node-ses version 2.2.1 :)

**Comment by markstos** [comment] 2020-04-14 18:49
What happens you follow the documented steps for debugging?

https://github.com/aheckmann/node-ses#debugging

**Comment by epegzz** [comment] 2020-04-14 18:53
Hey @markstos, I could actually pin down the issue to the `aws4` lib. So instead of using `node-ses` I tried using the `aws4` lib directly and could still reproduce the error.

And I found out that all works if I use the region `us-east-1`. But if I use `eu-central-1` I get the error message stated by OP.

So at least my problem does not origin in `node-ses`.

@SURVESHCHAUHANMARLABS What region are you using?

**Comment by epegzz** [comment] 2020-04-14 19:26
Okay, actually [I could fix](https://github.com/aheckmann/node-ses/pull/59) it within `node-ses` 😊

**Comment by markstos** [comment] 2020-04-14 20:26
@epegzz Perhaps we should switch our dependency directly the `aws-sdk`, which is now modularized.

Check out this out: https://www.npmjs.com/package/@aws-sdk/client-ses/v/1.0.0-beta.3

Cross reference with their API docs: 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html

Or
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SESV2.html

**Comment by epegzz** [comment] 2020-04-14 20:28
@markstos and this does not require to have the CLI installed locally? 🙂

**Comment by epegzz** [comment] 2020-04-14 20:44
Looks like it's a pure JS implementation👌 In that case, absolutely, always better to use 1st party software 👍

**Comment by epegzz** [comment] 2020-04-14 21:09
Okay, finally I could fix the issue: https://github.com/aheckmann/node-ses/pull/60 🎉

**Comment by epegzz** [comment] 2020-04-15 10:40
@markstos could you merge this PR and create a new release, please? :)

**Comment by markstos** [comment] 2020-04-16 13:50
The PR looks OK to me. I'll merge and release now, and go ahead close this issue. Thanks the troubleshooting and contribution!

**Closed by markstos** 2020-04-16 13:50 UTC

**Comment by markstos** [comment] 2020-04-16 13:55
> always better to use 1st party software

Just to comment on this. It _seems_ like it should be true, but the original AWS SES solution was part of a massive SDK, making it a huge, constantly changing dependency which was arguably worse then this simple library.

The situation is now is better, but not by a lot. AWS did break out a library just focuses on SES-- great-- but it contains no documentation of it's own, and it's even clear if the correct docs to reference are the "SES 1" or "SES 2" docs. Even the most basic usage it's documented in the NPM package they made.

So while I will always check first on the quality of a first-party library, in this case I think a lot of users are still better off with a simple and well-documented third-party library like this one.

One day if the quality of AWS SES package improves, I may switch myself!

My biggest complaint about this package is that it lacks native promise support. Hopefully that bugs someone else, too and they will contribute it.

**Comment by epegzz** [comment] 2020-04-16 14:10
> The PR looks OK to me. I'll merge and release now, and go ahead close this issue. Thanks the troubleshooting and contribution!

Thanks for the merge!

And yeah, fair points with the documentation. I guess they expect everyone to figure out how to use it based on the TypeScript specs? But yeah, I would not be looking forward using that lib as it is right now either, lacking any documentation.
